- name: Demo on Loops
  hosts: localhost
  connection: local
  tasks:
    - name: Print Fruit Name
      ansible.builtin.debug:
        msg: Fruit Name - {{ item }}
      loop:
        - main.tfvars
        - orange
        - grape
        - banana
    - name: Print Fruit Name and Quantity
      ansible.builtin.debug:
        msg: Fruti Name - {{ item.name }}, Quantity - {{ item.qty }}
      loop:
        - { name: Apple, qty: 100 }
        - { name: Orange, qty: 200 }
        - { name: grape, qty: 300 }
        - { name: banana, qty: 400 }