- name: Print parameters form parameter store
  hosts: all
  connection: local
  tasks:
    - name: Print Parameter
      ansible.builtin.debug:
        msg: Parameter - "{{ lookup('amazon.aws.aws_ssm', 'test.test') }}"