- name: Set up Frontend
  hosts: all
  become: yes
  tasks:
    - name: Installing Nginx Server
      ansible.builtin.yum:
        name: nginx
        state: latest

    - name: Remove directory
      ansible.builtin.file:
        path: /usr/share/nginx/html
        state: absent

    - name: creating directory
      ansible.builtin.file:
        path: /usr/share/nginx/html
        state: directory

    - name: Downloading new app content
      ansible.builtin.unarchive:
        src: https://roboshop-artifacts.s3.amazonaws.com/frontend.zip
        dest: /usr/share/nginx/html
        remote_src: yes

    - name: Configuring Reverse proxy server
      ansible.builtin.copy:
        src: roboshop.conf
        dest: /etc/nginx/default.d/roboshop.conf

    - name: Enabling and restarting Nginx Server
      ansible.builtin.systemd:
        name: nginx
        state: restarted
        enabled: true